#! /bin/bash

echo -n "Sisesta oma nimi: "
read nimi

echo "Tere tulemast, $nimi!"

echo -n "Sisesta oma sünniaasta: "
read aasta

vanus=$(( $(date +%Y) - aasta ))

echo "$nimi, sa oled $vanus aasta vana."
 
