#!/bin/bash

read -p "Sisesta ridade arv: " ridu
read -p "Sisesta tarnide arv reas: " tarnid

for i in $(seq 1 $ridu)
do
  echo -n "$i. "
  for ((j=1; j<=tarnid; j++))
  do
    echo -n "* "
  done
  echo
done
