#!/bin/bash

read -p "Sisesta ridade arv: " ridu
read -p "Sisesta tarnide arv reas: " tarnid

for ((i=1; i<=ridu; i++))
do
  echo -n "$i. "
  if [[ $i -eq 1 || $i -eq $ridu ]]; then
    for ((j=1; j<=tarnid; j++))
    do
      echo -n "* "
    done
  else
    echo -n "* "
    for ((j=2; j<tarnid; j++))
    do
      echo -n "  "
    done
    echo -n "*"
  fi
  echo
done
