#!/bin/bash

read -p "Sisesta ridade arv (1–99): " ridu

if ! [[ "$ridu" =~ ^[0-9]+$ ]]; then
    echo "Viga: Ainult täisarvud on lubatud."
    exit 1
fi

if [ "$ridu" -lt 1 ] || [ "$ridu" -ge 100 ]; then
    echo "Viga: Arv peab olema vahemikus 1 kuni 99."
    exit 1
fi

for ((i=1; i<=ridu; i++))
do
  echo -n "$i. "
  o_arv=$((ridu - i))
  t_star=$i

  for ((j=1; j<=o_arv; j++))
  do
    echo -n "o "
  done

  for ((k=1; k<=t_star; k++))
  do
    echo -n "* "
  done

  echo
done
