#! /bin/bash


echo -n "Sisesta kuu number: "
read kuu

if ! [[ "$kuu" =~ ^[0-9]+$ ]] || [ "$kuu" -lt 1 ] || [ "$kuu" -gt 12 ]; then
    echo "Vigane sisend: palun sisesta kuu number vahemikus 1 kuni 12"
elif [ "$kuu" -eq 12 ] || [ "$kuu" -eq 1 ] || [ "$kuu" -eq 2 ]; then
    echo "Praegu on talv"
elif [ "$kuu" -ge 3 ] && [ "$kuu" -le 5 ]; then
    echo "Praegu on kevad"
elif [ "$kuu" -ge 6 ] && [ "$kuu" -le 8 ]; then
    echo "Praegu on suvi"
elif [ "$kuu" -ge 9 ] && [ "$kuu" -le 11 ]; then
    echo "Praegu on sügis"
fi
