#! /bin/bash

tund=$(date +%H)

kasutaja="${USER^}"


if [ "$tund" -ge 6 ] && [ "$tund" -lt 12 ]; then
    echo "Tere hommikust, $kasutaja!"
elif [ "$tund" -ge 12 ] && [ "$tund" -lt 18 ]; then
    echo "Tere päevast, $kasutaja!"
elif [ "$tund" -ge 18 ] && [ "$tund" -lt 22 ]; then
    echo "Tere õhtust, $kasutaja!"
else
    echo "Head ööd, $kasutaja!"
fi
