#! /bin/bash

if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks:  ./paarsus 3"
    exit 1
fi

arv=$1

if ! [[ "$arv" =~ ^-?[0-9]+$ ]]; then
    echo "Sisesta täisarv."
    exit 1
fi

if [ $(( arv % 2 )) -eq 0 ]; then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
